letter = r'[a-z]'
var = r'[A-Z]'
expr = f'{letter}+'
alt_regex = f'(?:{expr}\|)*{expr}'
regex = f'(?:\({expr}\|{alt_regex}\)|{expr})'
plus = r'[ \t]*\+[ \t]*'
eq =  r'[ \t]*=[ \t]*'
equation = f'{var}{eq}(?:{regex}{var}(?:{plus}{regex}{var})*{plus})?{regex}(?:[ \t]|\n)*'
system = f'\n*(?:{equation})+'