title: Теория Формальных Языков
author: ''

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/SmEgDm/tfl
  path_to_book: labs
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: false
  extra_navbar: ''

sphinx:
  config:
    language: ru
    html_show_copyright: false

launch_buttons:
  binderhub_url: ''
